### PR TITLE
Pull request from the `bug_fixing` branch

### PR DESCRIPTION
**Pull request by jennykim1016**
After fixing the bug, make sure to merge it into master

### CODE REVIEW

**Comment by jennykim1016** [comment]
For 50 lenses with 100 observation epochs:

Before `size_calculate()`
changed_cornerplot

After `size_calculate()`
size fixed

Will start merging with master so that master will have the most up-to-date code. Magnitudes also make sense.

**Comment by jennykim1016** [comment]
Closing #60 -- fixed

**Comment by drphilmarshall** [comment]
Trying to interpret the structure in our cornerplot: I think we are seeing
a lot of color invariance (u to z) because the object is being dominated
either by the lens galaxy or the quasar image system - there just don't
seem to be many inbetween cases.

I think the tail at high[red] (u-z) color must be due to systems with a
dominant lens galaxy: the size is much bigger in the z band. It could be
interesting to include z-band magnitude, size, ellipticity to this
cornerplot, to help with the interpretation of various features in this
way. You could also make some selections based on these plots, and inspect
the resulting subsample.

**Comment by jennykim1016** [comment]
Hi @drphilmarshall ,

Thanks! I will do that. It takes some time to generate the new source and the new object catalog, so I just ran for 50 systems to check whether all the plots seem reasonable at the first place. In order to make some selections and inspect it, I think I will need more than 50 systems :) I will first run the script to make a new table and then inspect the subsamples.

**Pull request merged**
