### PR TITLE
Pull Request from obs_err branch

### PR DESCRIPTION
**Pull request by jennykim1016**
I am going to work on generating the mock data set! Null deblending is ready (moment_experiment).

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Very good! Can you assign a reviewer please, and let us know when you need
code review done by? You can also say something about what _kind_ of code
review you would like (eg just look for glaring errors, line by line
inspection for python style, advice on code structure, gaps in
documentation etc). By default you get a general review for everything but
this is this can be asking a lot of your reviewers!

**Comment by jennykim1016** [comment]
Hi Dr. Marshall and Mike,

I assigned Mike as a reviewer. It would be great if I could get a review on noticeable errors in the code and the general inspection of python style. By Wednesday would be great so that I could finalize the code before the Thursday meeting, but no rush please!

Thanks, and have a nice week! :)

**Review by mbaumer — COMMENTED** [review]
Hi Jenny, 
Nice work! A few cleanup steps would help me focus on functionality when reviewing your code:

1. The following temp file should be removed from the PR: python/desc/slrealizer/#null_deblend_v2.py#

2. There seem to be 4 versions of the same thing: python/desc/slrealizer/null_deblend.py, python/desc/slrealizer/null_deblend_v1.py, and a _v2 and _v3. Which one of these does the code actually use? We should only have one copy of this on the main branch.

3. python/desc/slrealizer/testing.py doesn't test anything, it just defines the chisq and KL functions. Can you rename this file or move these functions somewhere else?

4. In python/desc/slrealizer/Testing.ipynb, the final output is some first moments and a covariance matrix, but how can I tell if these numbers are correct? A "test" should compute something and compare it to a known value.

5. Finally,  python/desc/slrealizer/constant.py has a nice summary docstring at the beginning of the file. This immediately told me the purpose of this file, and what it is trying to do. Could you add similar summaries to SLRealizer.py, catalog.py, and deblend.py please? They're very helpful to reviewers in understanding why each file exists.
Thanks!
Mike

**Comment by jennykim1016** [comment]
Hi Mike,

1&2 : Sorry -- I thought my local repo and the github repo were synced, but I think I forgot to `git rm` after local `rm` commands. I deleted those unnecessary files!
4: Similarly, I should have removed this file from Git. `Testing.py` was used to experiment with some codes. The unit tests for gaussians are in `test.py`, which can be run with the command `nosetests`.
3 & 5 : I renamed the file / added summaries to the file.

Thank you so much for your help! :)

**Comment by jennykim1016** [comment]
I am not using this branch anymore, the most-to-date version is in `obs_err_ext`. Closing the pull request.

**Pull request closed without merging**
